# KiCost configuration file
# Create a copy of this file locally, called kibost_config_local.yaml
# kibost_config_local.yaml should NOT be shared as it contains API keys
# By default, kicost_config_local.yaml is in the .gitignore
# To run KiCost, you can run the following:
# ./kibot_launch.sh -v <VARIANT> --costs
kicost:
  version: 1
  # Prices are valid for a day
  cache_ttl: 1
  # # We will store the cache here:
  cache_path: ~/kicost_cache

# Add any API option here
# Avoid secrets
APIs:
  Digi-Key:
    # Digi-Key Client ID for a registered APP
    client_id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # Digi-Key Client Secret for a registered APP
    client_secret: xxxxxxxxxxxxxxxx

    # Use the sandbox server, doesn't count the usage, but returns old data
    # sandbox: false
    # Only enabled if the client_id and client_secret are defined
    enable: true
    # Directory for the APIs caches
    cache_path: ~/.cache/kicost/Digi-Key
  Mouser:
    # Mouser Part API key
    key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    # Only enabled if the key is defined
    enable: true
    # Directory for the APIs caches
    cache_path: ~/.cache/kicost/Mouser
  # Element14:
    # Element14 includes: Farnell, Newark and CPC
    # Element14 Product Search API key
    # key: XXXXXXXXXXXXXXXXXXXXXXXX
    # Only enabled if the key is defined
    # enable: false
    # Country used for Farnell queries.
    # Supported countries: BG,CZ,DK,AT,CH,DE,IE,IL,UK,ES,EE,FI,FR,HU,IT,LT,
    # LV,BE,NL,NO,PL,PT,RO,RU,SK,SI,SE,TR,CN,AU,NZ,HK,SG,MY,PH,TH,IN,KR,VN
    # farnell_country: UK
    # Country used for Newark queries.
    # Supported countries: US,CA,MX
    # newark_country: US
    # Country used for CPC queries.
    # Supported countries: UK,IE
    # cpc_country: UK
    # Directory for the APIs caches
    # cache_path: ~/.cache/kicost/Element14
  # Nexar:
    # Nexar client ID
    # client_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    # Nexar client secret
    # client_secret: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    # Only enabled if the client_id and client_secret are defined
    # enable: false
    # Country where we are buying
    # country: US
    # Directory for the APIs caches
    # cache_path: ./nexar
  TME:
    # TME token (anonymous or private)
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # TME application secret
    app_secret: xxxxxxxxxxxxxxxxxxxx
    # Only enabled if the token and app_secret are defined
    enable: true
    # Country where we are buying
    # country: US
    # Language for the texts
    # language: EN
    # Directory for the APIs caches
    cache_path: ~/.cache/kicost/TME
