# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2026 Daniel Kampert <DanielKampert@kampis-elektroecke>
#
# This file is part of KiCad Part-DB Integration.
#
# KiCad Part-DB Integration is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# KiCad Part-DB Integration is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Parser for KiCad BOM CSV files generated by the KiCad EDA tool."""

import csv
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List

@dataclass
class BOMEntry:
    """Represents a single BOM row from a KiCad BOM CSV file."""

    row: int
    quantity: int
    references: List[str]
    value: str
    datasheet: str
    footprint: str
    description: str
    manufacturer: str
    manufacturerPn: str

    @property
    def designatorPrefix(self) -> str:
        """Extract the alphabetic designator prefix from the first reference.

        Examples:
            C1003 -> C
            IC702 -> IC
            SW801 -> SW
            LED1001 -> LED
        """
        if (not self.references):
            return ""
        match = re.match(r'^([A-Z]+)', self.references[0], re.IGNORECASE)
        return match.group(1).upper() if match else ""

def parseBom(filepath: str) -> List[BOMEntry]:
    """Parse a KiCad BOM CSV file and return a list of BOM entries.

    The expected CSV header is:
        Row, Quantity Per PCB, References, Value, Datasheet,
        Footprint, Description, manf, manf#

    Args:
        filepath: Absolute or relative path to the BOM CSV file.

    Returns:
        List of BOMEntry objects, one per CSV row.

    Raises:
        FileNotFoundError: If the file does not exist.
        KeyError: If a required column is missing in the CSV.
    """
    entries: List[BOMEntry] = []

    with open(filepath, "r", encoding = "utf-8", newline = "") as csvFile:
        reader = csv.DictReader(csvFile)

        for row in reader:
            referencesRaw = row.get("References", "").strip()
            references = referencesRaw.split() if referencesRaw else []

            entry = BOMEntry(
                row = int(row["Row"]),
                quantity = int(row["Quantity Per PCB"]),
                references = references,
                value = row.get("Value", "").strip(),
                datasheet = row.get("Datasheet", "").strip(),
                footprint = row.get("Footprint", "").strip(),
                description = row.get("Description", "").strip(),
                manufacturer = row.get("manf", "").strip(),
                manufacturerPn = row.get("manf#", "").strip(),
            )
            entries.append(entry)

    return entries

def findBomFile(releaseDir: str) -> str:
    """Locate the BOM CSV file inside a KiCad release directory.

    The BOM is expected at: <release_dir>/Manufacturing/Assembly/*-bom.csv

    Args:
        release_dir: Root directory of the KiCad release.

    Returns:
        Absolute path string to the found BOM CSV file.

    Raises:
        FileNotFoundError: If no matching BOM file is found.
    """
    matches = sorted(Path(releaseDir).glob("Manufacturing/Assembly/*-bom.csv"))
    if (not matches):
        raise FileNotFoundError(
            f"No BOM CSV file found in '{release_dir}/Manufacturing/Assembly/'"
        )
    return str(matches[0])
