name: Diff

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

jobs:
  build:
    name: Generate a diff between the current feature branch and the main branch
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          path: modified
          submodules: recursive

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: original
          submodules: recursive

      - name: Create schematics diff
        run: |
          kicad-diff.py original/project/*.kicad_sch modified/project/*.kicad_sch --diff_mode red_green --all_pages --output_dir diff-schematics --no_reader --keep_pngs --resolution 400

      - name: Create layout diff
        run: |
          kicad-diff.py original/project/*.kicad_pcb modified/project/*.kicad_pcb --diff_mode red_green --all_pages --output_dir diff-layout --no_reader --keep_pngs --resolution 400

      - name: Upload Layout Diff
        uses: actions/upload-artifact@v4
        with:
          name: "diff-layout-${{ github.ref_name }}"
          path: diff-layout
          if-no-files-found: ignore

      - name: Upload Schematics Diff
        uses: actions/upload-artifact@v4
        with:
          name: "diff-schematics-${{ github.ref_name }}"
          path: diff-schematics
          if-no-files-found: ignore
